### ISSUE TITLE
运行 node index.js 出错  Cannot find module 'babel-core/register'

### ISSUE THREAD

**Issue by zsedcbm** [ericjjj/vms#6]
Error: Cannot find module 'babel-core/register'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\GitWorkSpace\vms\backend\index.js:6:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by ericjjj** [comment]
npm install
