### ISSUE TITLE
請問出現這段錯誤是發生了什麼事呢＠＠？

### ISSUE THREAD

**Issue by lostshin** [ericjjj/vms#8]
```
ＸＸＸＸＸＸ@chunde-MacBook-Air  ~/vms/backend   master  NODE_ENV=dev node index.js
module.js:472
    throw err;
    ^

Error: Cannot find module 'babel-core/register'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/chunlinlu/vms/backend/index.js:6:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by ericjjj** [comment]
@lostshin 请在 backend 目录下执行 `npm install`
