### ISSUE TITLE
貌似mongo配置错了，请教mongo怎么搞

### ISSUE THREAD

**Issue by ithack** [ericjjj/vms#9]
$ NODE_ENV=dev node index.js
=====================================================
VMS SERVICES START AT 2017-04-17 13:54:08
=====================================================
2017-04-17 13:54:08.877 DEBUG debug (9204) - Listening on port 3000

E:\前端测试dome\vms\backend\node_modules\connect-mongo\node_modules\mongodb\lib\
mongo_client.js:338
          throw err
          ^
MongoError: failed to connect to server [127.0.0.1:27017] on first connect [Mong
oError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (E:\前端测试dome\vms\backend\node_modules\connect-mongo\
node_modules\mongodb-core\lib\topologies\server.js:327:35)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (E:\前端测试dome\vms\backend\node_modules\connect-
mongo\node_modules\mongodb-core\lib\connection\pool.js:274:12)
    at Connection.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (E:\前端测试dome\vms\backend\node_modules\connect-mong
o\node_modules\mongodb-core\lib\connection\connection.js:177:49)
    at Socket.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1278:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by ericjjj** [comment]
你的 mongo 端口是 默认的 27017 么

**Comment by ericjjj** [comment]
请在 命令行中 测试下 `mongo`

**Comment by ithack** [comment]
@ericjjj 怎么测？

**Comment by ericjjj** [comment]
命令行 输入 mongo

**Comment by ericjjj** [comment]
然后回车

**Comment by ericjjj** [comment]
你安装 mongo 了么

**Comment by ithack** [comment]
@ericjjj 装了
![image](https://cloud.githubusercontent.com/assets/4329193/25083282/d0651e26-2388-11e7-844a-09fe7421ea14.png)

**Comment by ithack** [comment]
@ericjjj 搞定了 谢谢，我自己去研究下

**Comment by ericjjj** [comment]
好的 需要在配置文件里 配置 qiniu 的 key 你可以看看其他 issue https://github.com/ericjjj/vms/issues/7
